# 
# Copyright (c) 2026 Lukenar11 (Luke Matthes)
# MIT Licensed
# https://github.com/Lukenar11/MoleculeOS/blob/main/LICENSE
# 

COMMON_FLAGS += \
	-Ishell/include

include shell/src/interpreter/Makefile
include shell/src/interpreter/utils/Makefile

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)
