# 
# Copyright (c) 2026 Lukenar11 (Luke Matthes)
# MIT Licensed
# https://github.com/Lukenar11/MoleculeOS/blob/main/LICENSE
# 

COMMON_FLAGS += \
	-Ishell/include/interpreter

include shell/src/interpreter/Makefile

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)
