# 
# Copyright (c) 2026 Lukenar11 (Luke Matthes)
# MIT Licensed
# https://github.com/Lukenar11/MoleculeOS/blob/main/LICENSE
# 

COMMON_FLAGS += \
	-Iruntime/cpp/include \
	-Iruntime/cpp/include/utils \
	-Iruntime/apis/arch \
	-Iruntime/apis

include runtime/cpp/src/Makefile

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)
