# 
# Copyright (c) 2026 Lukenar11 (Luke Matthes)
# MIT Licensed
# https://github.com/Lukenar11/MoleculeOS/blob/main/LICENSE
# 

COMMON_FLAGS += -Ikernel/include \
				-Ikernel/include/filesystem \
				-Ikernel/include/heap \

include kernel/src/Makefile

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)
