# 
# Copyright (c) 2026 Lukenar11 (Luke Matthes)
# MIT Licensed
# https://github.com/Lukenar11/MoleculeOS/blob/main/LICENSE
# 

COMMON_FLAGS += \
	-Ikernel/include

include kernel/src/filesystem/Makefile
include kernel/src/heap/Makefile
include kernel/src/system/Makefile
include kernel/src/Makefile

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)
