# 
# Copyright (c) 2026 Lukenar11 (Luke Matthes)
# MIT Licensed
# https://github.com/Lukenar11/MoleculeOS/blob/main/LICENSE
# 

COMMON_FLAGS += -Idrivers/include/ata \
				-Idrivers/include/ps2 \
				-Idrivers/include/vga \
				-Idrivers/include/utils \

include drivers/src/Makefile

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)
