# 
#    Copyright (c) 2026 Lukenar11 (Luke Matthes)
#    MIT Licensed
#    https://github.com/Lukenar11/MoleculeOS/blob/main/LICENSE
# 

OBJS += \
	$(BUILD)/linear_area.o

$(BUILD)/linear_area.o: kernel/src/heap/linear_area.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@
