# 
# Copyright (c) 2026 Lukenar11 (Luke Matthes)
# MIT Licensed
# https://github.com/Lukenar11/MoleculeOS/blob/main/LICENSE
# 

COMMON_FLAGS += \
	-Iarch/i386/runtime/include \

include arch/i386/runtime/src/Makefile

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)
