# 
#    Copyright (c) 2026 Lukenar11 (Luke Matthes)
#    MIT Licensed
#    https://github.com/Lukenar11/MoleculeOS/blob/main/LICENSE
# 

OBJS += \
	$(BUILD)/kernel_main.o \

$(BUILD)/kernel_main.o: kernel/src/kernel_main.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@
